# Generated by Django 2.2 on 2019-12-24 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rumy_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermodel',
            name='age',
        ),
        migrations.RemoveField(
            model_name='usermodel',
            name='bio',
        ),
    ]
